Make atmos_prep job work using GFSv17 and new COM structure
NOAA-EMC/GEFS pull request #119
Opened 2023-04-07 02:25 UTC by XianwuXue-NOAA

Since the rsfcanl.nc is not variable in early cycle enkf, so I copy the c00 data to all ensemble members, I will do the change after rsfcanl.nc is available. 

For ensemble member path, I still use c00, p01, ..., p30 for this time, I will open another issue to change the member path from c00, p01, .. to mem000, mem001, ... after all the atm workflow is ready.

2023-04-13 05:16 UTC, WalterKolczynski-NOAA requested changes
This probably should've been a few different PRs. (at the very least, changes to use `os.path.join()` should've been separate). A bit hypocritical of me given the COM refactor PR, but I do usually try to keep PRs to one thing at a time.

Outside the scope of this PR, but we definitely have too much machine-dependent code all over the place.

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_ATMOS_PREP
> +export ROTDIR=${ROTDIR:-$(compath.py -o $NET/${ver})}
My understanding is `ROTDIR` should not use `compath.py` (see https://github.com/NOAA-EMC/global-workflow/issues/289), since `ROTDIR` belongs to the current model and not an upstream package.

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on parm/parm_gefs/gefs.parm
It would probably be better if these got moved into a `parm/config/` directory like GFS has, with the file names changed to `config.x`.

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_ATMOS_PREP
> +export ROTDIR=${ROTDIR:-$(compath.py -o $NET/${ver})}
Even if you keep `compath.py` for now, you're missing the `${envir}`.

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on parm/parm_gefs/gefs_atmos_prep.parm
> +#export cycp=$(echo $pdycycp|cut -c9-10)
Go ahead and delete these

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on rocoto/bin/hera/atmos_prep.sh
> +module list
Not much point in listing right before you purge/reset

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on rocoto/bin/hera/atmos_prep.sh
> +module purge
You should use `module reset` rather than `module purge`.

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on rocoto/bin/hera/atmos_prep.sh
> +ver=${ver:-$(echo ${gefs_ver}|cut -c1-5)}
```suggestion
ver=${gefs_ver:0:5}
```

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on rocoto/bin/hera/atmos_prep.sh
> +ver=${ver:-$(echo ${gefs_ver}|cut -c1-5)}
```suggestion
ver=${ver%${ver##v+([0-9]).+([0-9])}}
```

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on rocoto/bin/hera/atmos_prep.sh
> +ver=${ver:-$(echo ${gefs_ver}|cut -c1-5)}
This is the bash expansion equivalent of the regex `r'v\d+\.\d+'`.

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on rocoto/bin/wcoss2/common.sh
> +    if [[ $CASEHR == "C48" ]]; then
Use a `case` statement to make expanding this easier

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on rocoto/bin/wcoss2/common.sh
> +      export COMPATH=${WORKDIR}/$envir/com/${NET}:/lfs/h2/emc/ens/noscrub/xianwu.xue/GEFS_v13/z_DATA/lfs_C96_C48_NOIAU_anal/h1/ops/prod/com/gfs
How is the `:` being processed?

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on rocoto/py/GEFS_Crontab.py
> +    import sys, os
PEP-8 says one import per line
```suggestion
    import sys
    import os
```

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on rocoto/py/GEFS_XML.py
> +    import os
PEP-8: imports should only appear at the top of the file

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on rocoto/py/user_hera.conf
> +DATA_DIR                        = &WORKDIR;/dev/com/gefs/v12.3
Shouldn't this use `gefs_ver`?

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on scripts/exgefs_atmos_prep.sh
> +#echo "$(date -u) begin $(basename $BASH_SOURCE)"
Delete the old code

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on sorc/link_gefs.sh
> +  $LINK ${sPath}/tocsbufr.x ../exec/
These should all already be in `global-workflow.fd/exec` without the need to dig deeper into the tree.

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on sorc/link_gefs.sh
> +  lUsh=`ls ../sorc/global-workflow.fd/ush/wave_*` #"wave_ens_bull.sh wave_ens_stat.sh wave_grib2_sbs.sh wave_grid_interp_sbs.sh wave_grid_moddef.sh wave_outp_spec.sh wave_prnc_cur.sh wave_prnc_ice.sh
```suggestion
lUsh=$(ls ../sorc/global-workflow.fd/ush/wave_*)
```

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on sorc/link_gefs.sh
> +  lUsh=`ls ../sorc/global-workflow.fd/ush/wave_*` #"wave_ens_bull.sh wave_ens_stat.sh wave_grib2_sbs.sh wave_grid_interp_sbs.sh wave_grid_moddef.sh wave_outp_spec.sh wave_prnc_cur.sh wave_prnc_ice.sh
Though I'm not sure using a wildcard is a great idea.

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on sorc/link_gefs.sh
> +    sFile=$(basename ${sFile})
Is it necessary to get the basename?

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on ush/gefs_atmos_prep.sh
> +#fi
Delete the old code.

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on ush/gefs_atmos_prep.sh
> +export OUTDIR=${COM_ATMOS_INPUT} # ${COMOUT}/$mem/atmos/INPUT
`generate_com` should be called at the j-job level and be read-only whenever possible. For this job, that will mean also pulling up the `mem` (and `memchar`, see correction) definition up to the j-job. Also, this should be:

```suggestion
YMD=${PDY} HH=${cyc} MEMDIR=${memchar} generate_com -rx OUTDIR:COM_ATMOS_INPUT_TMPL
```

In GFS, I replaced all these indirect variable names (like `INDIR`, `OUTDIR`) with the actual location (`COM_ATMOS_INPUT`), but we can skip that for now until we are sure my effort there isn't rejected.

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on ush/gefs_atmos_prep.sh
> +fi
We no longer use different fix directories, even when fractional grid is off. See https://github.com/NOAA-EMC/global-workflow/pull/1242

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on ush/gefs_atmos_prep.sh
> +fi
Also, OCNRES should be defined elsewhere (probably `gefs.parm`, which should become `config.base`).

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on ush/gefs_atmos_prep.sh
> +  export ATM_FILES_INPUT="gfs.t${cyc}z.atmanl.nc"
This is only one file, the variable name shouldn't be plural.
```suggestion
  export ATM_FILE_INPUT="gfs.t${cyc}z.atmanl.nc"
```

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on ush/gefs_atmos_prep.sh
> +  ATMFILE=${COMINgfs}/atmos/${ATM_FILES_INPUT} #gfs.t${cyc}z.atmanl.nc
This is not going to be the correct path after the COM refactor is merged. Ideally these should be set using a template. Could use the same template as GEFS, though that will break if GEFS and GFS ever have different templates. We can either ignore that risk (since they should not change often and GEFS should merge with GFS for v14), or work around it by renaming the GEFS templates (e.g. `COM_GEFS_ATMOS_INPUT`) to avoid clobbering the GFS templates with the GEFS templates (or vice versa). Probably just ignore that risk (really, GEFS can just reuse the GFS templates instead of defining its own).

Using templates, it will be something like this set in the j-job:
```
YMD=${PDY} HH=${cyc} RUN="gdas" generate_com -rxCOM_ATMOS_ANALYSIS_GFS:COM_ATMOS_ANALYSIS
```

Then this will become
```suggestion
  ATMFILE=${COM_ATMOS_ANALYSIS_GFS}/${ATM_FILE_INPUT}
```

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on ush/gefs_atmos_prep.sh
> +    ATMFILE="${COMINenkfgfs}/$memchar/atmos/${ATM_FILES_INPUT}"  #gfs.t${cycp}z.atmanl.nc"
See above. Also, `ratmanl.nc` does not appear to be an output of the GFS system. Only see `enkfgfs.t00z.ratmi003.nc`, `enkfgfs.t00z.ratmi009.nc`, and `enkfgfs.t00z.ratminc.nc` in my trees. Am I missing a file and need to hunt down an error?

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on ush/gefs_atmos_prep.sh
> +  SFCFILE="${COMINgfs}/atmos/${SFC_FILES_INPUT}"
See above

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on ush/gefs_atmos_prep.sh
> +      COMDIR2=${COM_ATMOS_INPUT} #${echo "${!COM_ATMOS_INPUT_TMPL}"} # $(echo "${!COM_ATMOS_INPUT_TMPL}" | envsubst) #${COM_ATMOS_INPUT} #$COMOUT/${mem2}/atmos/INPUT #init/$mem2
```suggestion
YMD=${PDY} HH=${cyc} MEMDIR=${mem2} generate_com COMDIR2:COM_ATMOS_INPUT_TMPL
```
(It is only used locally, no need to export.)

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on versions/fix.ver
Should just use the GFS file instead of duplicating it.

2023-04-13 05:16 UTC, WalterKolczynski-NOAA commented on parm/config/config.com
Should probably just use the GFS `config.com` (see long-winded comment about templates).

2023-04-13 14:51 UTC, XianwuXue-NOAA commented on parm/parm_gefs/gefs.parm
Thanks for your suggestions, I have created the part/config directory to host all config.x from g-w with or without changes. And put the original gefs parm files to the parm/parm_gefs/ with some modification based on the new COM refactor. After this, we can figure out how to merge parm/parm_gefs into config.x or only reuse the config.x in g-w repo and add some specific configuration in gefs repo. Therefore, I think it is better to keep parm/parm_gefs/ in this stage

2023-04-13 14:59 UTC, XianwuXue-NOAA commented
> This probably should've been a few different PRs. (at the very least, changes to use `os.path.join()` should've been separate). A bit hypocritical of me given the COM refactor PR, but I do usually try to keep PRs to one thing at a time.
> 
> Outside the scope of this PR, but we definitely have too much machine-dependent code all over the place.

Thanks Walter. Yes, I agree, at least `os.path.join()` should be in one PR. I may create a new PR for this. 
Yes, there is a lot of machine=dependent code, and you may see that I am starting to remove such codes and also some legacy code. I will continue doing this in the following PR. Maybe some of the changes will not close to that PR, however, when I found some codes can be deleted or changed (minor changes), then I will do it in the PR

2023-04-13 20:47 UTC, XianwuXue-NOAA commented on jobs/JGEFS_ATMOS_PREP
> +export ROTDIR=${ROTDIR:-$(compath.py -o $NET/${ver})}
This is based on export COMOUT=${COMOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDY}/$cyc/$COMPONENT} in the current GEFSv12 production. When adding "-o", it does not need the ${envir}, but it only works on WCOSS2.

2023-04-13 20:49 UTC, XianwuXue-NOAA commented on rocoto/bin/hera/atmos_prep.sh
> +module list
The original design is to list the modules before the purge to double check whether the job can load module properly. Yes, it can be deleted.

2023-04-13 20:50 UTC, XianwuXue-NOAA commented on rocoto/bin/hera/atmos_prep.sh
> +module purge
No problem. I will check what is the difference between reset and purge since I never use reset before

2023-04-13 20:53 UTC, XianwuXue-NOAA commented on rocoto/bin/hera/atmos_prep.sh
> +ver=${ver:-$(echo ${gefs_ver}|cut -c1-5)}
So which one should be better? ver=${gefs_ver:0:5} or ver=${ver%${ver##v+([0-9]).+([0-9])}}?

2023-04-13 21:10 UTC, XianwuXue-NOAA commented on rocoto/bin/wcoss2/common.sh
> +      export COMPATH=${WORKDIR}/$envir/com/${NET}:/lfs/h2/emc/ens/noscrub/xianwu.xue/GEFS_v13/z_DATA/lfs_C96_C48_NOIAU_anal/h1/ops/prod/com/gfs
`"` is to separate different paths. Then `compath.py` can find the right path from `${COMPATH}`

2023-04-13 21:13 UTC, XianwuXue-NOAA commented on rocoto/py/GEFS_Crontab.py
> +    import sys, os
I also did changes for other scripts

2023-04-13 21:15 UTC, XianwuXue-NOAA commented on rocoto/py/GEFS_XML.py
> +    import os
I think the imports are in different function will be easier to manage and we don't need to go to top to add or delete imports. However, If PEP-8 has this rule, I will do such changes.

2023-04-13 21:17 UTC, XianwuXue-NOAA commented on rocoto/py/user_hera.conf
> +DATA_DIR                        = &WORKDIR;/dev/com/gefs/v12.3
I was thinking how to add it and how to make pyGEFS to get the gefs_ver value from the run_ver.

2023-04-13 21:20 UTC, XianwuXue-NOAA commented on sorc/link_gefs.sh
> +  $LINK ${sPath}/tocsbufr.x ../exec/
Yes, if gefs uses the built g-w, then some of the exec will be copy/link to the g-w.fd/exec, however, gefs will not run link.sh in global-workflow.fd, so some of the exec files will not in g-w.fd/exec. This is not a big deal and we can decide in the future.

2023-04-13 21:23 UTC, XianwuXue-NOAA commented on sorc/link_gefs.sh
> +  lUsh=`ls ../sorc/global-workflow.fd/ush/wave_*` #"wave_ens_bull.sh wave_ens_stat.sh wave_grib2_sbs.sh wave_grid_interp_sbs.sh wave_grid_moddef.sh wave_outp_spec.sh wave_prnc_cur.sh wave_prnc_ice.sh
Any suggestions are welcome. This design is just to shorten the lines of the script. And will do other changes when I do the other jobs, especially for fcst job.

2023-04-13 21:27 UTC, XianwuXue-NOAA commented on sorc/link_gefs.sh
> +    sFile=$(basename ${sFile})
No. Thanks for pointing this out. I will delete it and do the corresponding changes for the following lines.

2023-04-13 21:35 UTC, XianwuXue-NOAA commented on ush/gefs_atmos_prep.sh
> +  export ATM_FILES_INPUT="gfs.t${cyc}z.atmanl.nc"
Good insight! Thanks.

2023-04-13 21:38 UTC, XianwuXue-NOAA commented on ush/gefs_atmos_prep.sh
> +    ATMFILE="${COMINenkfgfs}/$memchar/atmos/${ATM_FILES_INPUT}"  #gfs.t${cycp}z.atmanl.nc"
When `DOIAU=no`. Since GEFS will not use IAU

2023-04-14 04:59 UTC, WalterKolczynski-NOAA commented on rocoto/bin/hera/atmos_prep.sh
> +module purge
NCO wants us to use reset since the move to WCOSS2. I'm surprised they didn't ask you to switch for the port (they did for GFS). It restores the base lmod environment instead of unloading all modules, but also drops any additional `module use` you may have added locally. On dev machines, you need to `LMOD_SYSTEM_DEFAULT_MODULES='contrib'` first because the admins haven't set it yet. You can look and see how workflow does it: https://github.com/NOAA-EMC/gfs-utils/blob/develop/ush/module-setup.sh

Really, you should probably be using that script, just like GW does. You'll already be getting it as part of the GW checkout.

2023-04-14 05:03 UTC, WalterKolczynski-NOAA commented on rocoto/bin/hera/atmos_prep.sh
> +ver=${ver:-$(echo ${gefs_ver}|cut -c1-5)}
The pattern matching one (`ver=${ver%${ver##v+([0-9]).+([0-9])}}`). That will work even if the `major.minor` has a different number of digits.

2023-04-14 05:04 UTC, WalterKolczynski-NOAA commented on rocoto/bin/wcoss2/common.sh
> +      export COMPATH=${WORKDIR}/$envir/com/${NET}:/lfs/h2/emc/ens/noscrub/xianwu.xue/GEFS_v13/z_DATA/lfs_C96_C48_NOIAU_anal/h1/ops/prod/com/gfs
Okay, so it is an actual `PATH`-like variable that `compath.py` uses.

2023-04-14 05:06 UTC, WalterKolczynski-NOAA commented on sorc/link_gefs.sh
> +  lUsh=`ls ../sorc/global-workflow.fd/ush/wave_*` #"wave_ens_bull.sh wave_ens_stat.sh wave_grib2_sbs.sh wave_grid_interp_sbs.sh wave_grid_moddef.sh wave_outp_spec.sh wave_prnc_cur.sh wave_prnc_ice.sh
Go ahead and keep the wildcard for now. We can go back to an explicit list later if we want. Do use `$( )` and not backticks though.

2023-04-14 05:08 UTC, WalterKolczynski-NOAA commented on ush/gefs_atmos_prep.sh
> +  ATMFILE=${COMINgfs}/atmos/${ATM_FILES_INPUT} #gfs.t${cyc}z.atmanl.nc
After discussing with @aerorahul, we agree GEFS should just use the GFS `config.com` for templates.

2023-04-14 05:09 UTC, WalterKolczynski-NOAA commented on ush/gefs_atmos_prep.sh
> +    ATMFILE="${COMINenkfgfs}/$memchar/atmos/${ATM_FILES_INPUT}"  #gfs.t${cycp}z.atmanl.nc"
But what about enkfgfs? That's where the problem lies.

2023-04-14 05:09 UTC, WalterKolczynski-NOAA commented on parm/config/config.com
After discussing with @aerorahul, we agree GEFS should just use the GFS config.com for templates.

2023-04-14 13:05 UTC, XianwuXue-NOAA commented on rocoto/bin/hera/atmos_prep.sh
> +module purge
No problem. I will use it in another PR.

2023-04-14 13:11 UTC, XianwuXue-NOAA commented on ush/gefs_atmos_prep.sh
> +    ATMFILE="${COMINenkfgfs}/$memchar/atmos/${ATM_FILES_INPUT}"  #gfs.t${cycp}z.atmanl.nc"
When `set DOIAU=NO`, then enkfgfs will generate ratmanl.nc. This function was added by Travis.

2023-04-17 19:24 UTC, XianwuXue-NOAA commented on ush/gefs_atmos_prep.sh
> +  export ATM_FILES_INPUT="gfs.t${cyc}z.atmanl.nc"
`ATM_FILES_INPUT` is the input for `chgres_cube.sh`

2023-04-18 01:32 UTC, XianwuXue-NOAA commented
@WalterKolczynski-NOAA I have modified and could you please review my changes? Thanks.

2023-04-19 00:20 UTC, WalterKolczynski-NOAA requested changes
Almost there

2023-04-19 00:20 UTC, WalterKolczynski-NOAA commented on rocoto/bin/hera/atmos_prep.sh
> +#ver=${ver%${ver##v+([0-9]).+([0-9])}}
Any reason not to use this one?

2023-04-19 00:45 UTC, XianwuXue-NOAA commented on rocoto/bin/hera/atmos_prep.sh
> +#ver=${ver%${ver##v+([0-9]).+([0-9])}}
My bad. I am checking how it work: ver=${ver%${ver##v+([0-9]).+([0-9])}} if there is no ver=${gefs_ver:0:5}

2023-04-19 01:43 UTC, WalterKolczynski-NOAA approved these changes

2023-04-19 01:46 UTC, merged