Make atmos_fcst job work using GFSv17 and new COM structure
NOAA-EMC/GEFS pull request #120
Opened 2023-04-26 17:44 UTC by XianwuXue-NOAA

The job works on both WCOSS2 and HARA.

2023-04-26 17:56 UTC, XianwuXue-NOAA commented on parm/config/config.ufs
> +#export kchunk3d=1
Lines 210~252 are for GEFS fcst job, especially for d16_35 and chem

2023-04-26 18:30 UTC, XianwuXue-NOAA commented on parm/parm_gefs/gefs_fcst.parm
> +        export FIELD_TABLE="$HOMEgfs/parm/parm_fv3diag/chm_field_table_gfdl"
This is for chem, maybe we don't use it in gefs.v13

2023-04-26 18:32 UTC, XianwuXue-NOAA commented on parm/parm_gefs/gefs_fcst.parm
> +    # Write more variables to output
In original config.fcst, there is no condition for `gefs`

2023-04-26 18:32 UTC, XianwuXue-NOAA commented on parm/parm_gefs/gefs_fcst.parm
> +    # Write more variables to output
@WalterKolczynski-NOAA @aerorahul

2023-04-26 19:11 UTC, XianwuXue-NOAA commented
@WalterKolczynski-NOAA @aerorahul Could you please review my changes for fcst job? I have a few comments for the config files, could you also give me some suggestions? I have ran c00, p01 and p02 (C48) succeeded on Hera, but failed for p02 on WCOSS2 because of instability of the model.

2023-04-27 05:38 UTC, WalterKolczynski-NOAA requested changes
Instead of duplicating the contents of GFS config files to make a few changes, you should be making changes to the config files in global workflow to support GEFS and/or adding config files that just change the things that are different. We want GEFS to run more more like GFS.

2023-04-27 05:38 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +  last_date=$($NDATE -$WAVHCYC $CDATE)
```suggestion
  last_date=$(${NDATE} -${WAVHCYC} "${PDY}${cyc}")
```

2023-04-27 05:38 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +  last_cyc=$(echo $last_date | cut -c9-10)
```suggestion
  last_PDY=${last_date:0:8}
  last_cyc=${last_date:8:2}
```

2023-04-27 05:38 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +export ROTDIR=${ROTDIR:-$(compath.py $envir/com/$NET/${ver})}
These should no longer be necessary with the templates. `$ROTDIR` should be defined in the job card.
```suggestion
```

2023-04-27 05:38 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +export memchar=$(echo $RUNMEM|cut -c3-5)
```suggestion
declare -rx memchar=${RUNMEM:2:3}
```

2023-04-27 05:38 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +export memchar=$(echo $RUNMEM|cut -c3-5)
Really, we should just be moving on from p## and use mem###.

2023-04-27 05:38 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +echo "COM_ATMOS_MASTER: " ${COM_ATMOS_MASTER}
This is now unnecessary. `generate_com()` echoes the assignements.

```suggestion
```

2023-04-27 05:38 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +echo "COM_ATMOS_RESTART_PREV: " ${COM_ATMOS_RESTART_PREV}
```suggestion
```

2023-04-27 05:38 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +  export WRDIR=${WRDIR:-$(compath.py $envir/com/$NET/${ver})}/${RUN}.${last_PDY}/$last_cyc/wave/restart
```suggestion
```

2023-04-27 05:38 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +  echo "FATAL ERROR in ${BASH_SOURCE}: $job failed!"
```suggestion
  echo "FATAL ERROR in ${BASH_SOURCE[0]}: $job failed!"
```

2023-04-27 05:38 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +echo "$(date -u) end ${BASH_SOURCE}"
Not necessary with the postamble
```suggestion
```

2023-04-27 05:38 UTC, WalterKolczynski-NOAA commented on scripts/exgefs_forecast.sh
> +  echo "FATAL ERROR in ${BASH_SOURCE}: received a non-zero return code from $FORECASTSH"
```suggestion
  echo "FATAL ERROR in ${BASH_SOURCE[0]}: received a non-zero return code from $FORECASTSH"
```

2023-04-27 05:38 UTC, WalterKolczynski-NOAA commented on scripts/exgefs_forecast.sh
> +echo "$(date -u) end ${BASH_SOURCE}"
```suggestion
echo "$(date -u) end ${BASH_SOURCE[0]}"
```

2023-04-27 05:38 UTC, WalterKolczynski-NOAA commented on scripts/exgefs_forecast.sh
Much of this should be in a config file.

2023-04-27 15:20 UTC, XianwuXue-NOAA commented on jobs/JGEFS_FORECAST
> +export memchar=$(echo $RUNMEM|cut -c3-5)
OK. I will open another issue to do it. for c00->000, p01->001, how about **aer**?

2023-04-27 15:21 UTC, XianwuXue-NOAA commented on jobs/JGEFS_FORECAST
> +echo "COM_ATMOS_MASTER: " ${COM_ATMOS_MASTER}
this is just echo them for me. I will delete them now.

2023-04-27 15:31 UTC, XianwuXue-NOAA commented on scripts/exgefs_forecast.sh
in config.fcst in g-w? If it is, you and @aerorahul should determine can I use `cdump=gefs`? or only use `RUN=gefs`? If you want to use run=gefs, then we should modify the config* in g-w to use RUN instead of `cdump`

2023-04-27 15:40 UTC, XianwuXue-NOAA commented on jobs/JGEFS_FORECAST
> +  export WRDIR=${WRDIR:-$(compath.py $envir/com/$NET/${ver})}/${RUN}.${last_PDY}/$last_cyc/wave/restart
If you want to remove WRDIR, then I think I can remove the whole block. However, this PR is only for atmos. So I will not test these changes. I plan when I do the coupled, I can modify the other statements not related to atmos.

2023-04-27 15:42 UTC, XianwuXue-NOAA commented
@WalterKolczynski-NOAA I have submitted a few commits based on your comment. When you have time, please review it.

2023-04-27 18:17 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +export memchar=$(echo $RUNMEM|cut -c3-5)
Leave it as aer for now.

2023-04-27 18:20 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +  export WRDIR=${WRDIR:-$(compath.py $envir/com/$NET/${ver})}/${RUN}.${last_PDY}/$last_cyc/wave/restart
You already have it farther down as `COM_WAVE_RESTART_PREV`, which is what the scripts in global-workflow will look for now (though this is untested and may need additional work).

2023-04-27 18:23 UTC, WalterKolczynski-NOAA commented on scripts/exgefs_forecast.sh
Per the slack and in-person conversations, make GEFS versions of the config files and then make sure these settings are defined in there.

2023-04-28 16:42 UTC, XianwuXue-NOAA commented
@WalterKolczynski-NOAA @aerorahul I have moved some vars from ex-script of fcst to config.fcst and also did other modification. Please review my changes. Thanks

2023-05-01 19:19 UTC, XianwuXue-NOAA commented
@WalterKolczynski-NOAA @aerorahul When you have time, could you review my changes for this PR? Thanks.

2023-05-02 05:34 UTC, WalterKolczynski-NOAA requested changes
Didn't complete the review of the config files. It seems like a lot of GEFS settings were tacked on to GFS settings without considering whether they are still needed or to update them to match the GFS style (for instance, using `$cplchm` for branching instead of `$DO_AERO`). Many settings have been updated for GFS v17/GEFS v13 and we should defer to the new settings as given in GFS unless there is a good reason to deviate (like turning on stochastic physics for some members). Please carefully review all of the settings and determine whether it is conflicting with an existing setting elsewhere. If you have any trouble determining whether a setting should be overridden for GEFS, I'll help and if necessary we'll ask MDAB.

Also, note the changes that were made in the NOAA-EMC/global-workflow#1509. You've updated the commit hash, but there are changes to the config files that will need to be duplicated here.

2023-05-02 05:34 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +export ROTDIR=${ROTDIR:-$(compath.py $envir/com/$NET/${ver})}
This should be defined before the j-job is called, and definitely should not use `compath.py`. `compath.py` should only be used for external packages (GFS, tracker, etc.).

2023-05-02 05:34 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +#export APRUN_FV3="mpiexec -n ${npe_fcst} -ppn ${npe_node_fcst} --cpu-bind depth --depth ${NTHREADS_FV3}"
Please remove the dead code.

2023-05-02 05:34 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +export CDATE=$PDY$cyc
We are avoiding using CDATE for the most part. I don't think this is even being used here after it is defined.
```suggestion
```

2023-05-02 05:34 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +    echo "FATAL ERROR in ${BASH_SOURCE}: Error while loading parm file ${config_path}/config.${config}"
`$BASH_SOURCE` is an array so should always specify an index, even if BASH defaults to the first element when none is provided (shellcheck will complain about this).
```suggestion
    echo "FATAL ERROR in ${BASH_SOURCE[0]}: Error while loading parm file ${config_path}/config.${config}"
```

2023-05-02 05:34 UTC, WalterKolczynski-NOAA commented on parm/config/config.base
>  #export USHgfs=${HOMEgfs}/ush
Remove all this dead code.

2023-05-02 05:34 UTC, WalterKolczynski-NOAA commented on parm/config/config.base
> +    echo "Unrecognized APP: ${1}"
```suggestion
    echo "Unrecognized APP: ${APP}"
```

2023-05-02 05:34 UTC, WalterKolczynski-NOAA commented on parm/config/config.base
> +fi
GEFS has no DA of its own, does this need to be included?

2023-05-02 05:34 UTC, WalterKolczynski-NOAA commented on parm/config/config.fcst
> +#-----
Remove dead code

2023-05-02 05:34 UTC, WalterKolczynski-NOAA commented on parm/config/config.fcst
> +echo "END: config.fcst"
But this is not the end of `config.fcst`

2023-05-02 05:34 UTC, WalterKolczynski-NOAA commented on parm/config/config.fcst
> +export cplwav=${cplwav:-.true.}
This will override the `$APP` setting up-script.

2023-05-02 05:34 UTC, WalterKolczynski-NOAA commented on parm/config/config.fcst
> +R2=$(echo $RUNMEM|cut -c4-5)
```suggestion
R2=${RUNMEM:3:2}
```

2023-05-02 05:34 UTC, WalterKolczynski-NOAA commented on parm/config/config.fcst
> +    export AERO_EMIS_FIRE=$( echo "${AERO_EMIS_FIRE:-none}" | awk '{ print tolower($1) }' )
```suggestion
    export AERO_EMIS_FIRE="${AERO_EMIS_FIRE,,}"
```

2023-05-02 05:34 UTC, WalterKolczynski-NOAA commented on parm/config/config.fcst
> +if [[ "$DO_WAVE" = "YES" && "$WAVE_CDUMP" != "gdas" ]]; then
```suggestion
if [[ "$DO_WAVE" = "YES" ]]; then
```

2023-05-02 05:34 UTC, WalterKolczynski-NOAA commented on parm/config/config.fcst
> +fi
I think this has all been superseded by other code/settings coming over from GFS.
```suggestion
```

2023-05-02 05:34 UTC, WalterKolczynski-NOAA commented on parm/config/config.fcst
> +export FNSOTC=$FIX_AM/global_soiltype.statsgo.t$MTNRSL.rg.grb
These are all defined in forecast_postdet and we should use the values there, as they have been updated for the newer model.

2023-05-02 05:34 UTC, WalterKolczynski-NOAA commented on rocoto/bin/hera/forecast_hr.sh
> +export ROTDIR=${COMROOT}/gefs/${ver}
For development, I don't think we need to add the additional unnecessary directory levels that NCO is.

```suggestion
# Assuming $EXPDIR is already built into $COMROOT
ROTDIR=${COMROOT}
```

2023-05-02 05:34 UTC, WalterKolczynski-NOAA commented on rocoto/bin/hera/forecast_hr.sh
> +export ROTDIR_GFS=${HOMEdata}/gfs/${gfs_ver}
Same here. For GFS development we don't include the extra directory levels NCO does. For operations, this needs to use `compath.py`, since GFS is an external package.

2023-05-02 12:12 UTC, XianwuXue-NOAA commented on jobs/JGEFS_FORECAST
> +export ROTDIR=${ROTDIR:-$(compath.py $envir/com/$NET/${ver})}
Is it the NCO new requirements? Because all the compath.py are in j-job in the current production.

2023-05-02 12:14 UTC, XianwuXue-NOAA commented on jobs/JGEFS_FORECAST
> +#export APRUN_FV3="mpiexec -n ${npe_fcst} -ppn ${npe_node_fcst} --cpu-bind depth --depth ${NTHREADS_FV3}"
Will delete it in the next commit

2023-05-02 12:20 UTC, XianwuXue-NOAA commented on jobs/JGEFS_FORECAST
> +export CDATE=$PDY$cyc
The CDATE is used for the config.nsst in g-w. If there is no CDATE defined, then it will fail

2023-05-02 12:21 UTC, XianwuXue-NOAA commented on jobs/JGEFS_FORECAST
> +    echo "FATAL ERROR in ${BASH_SOURCE}: Error while loading parm file ${config_path}/config.${config}"
Will in the next commit

2023-05-02 12:25 UTC, XianwuXue-NOAA commented on parm/config/config.base
>  #export USHgfs=${HOMEgfs}/ush
OK. I will delete the dead code.

2023-05-02 12:28 UTC, XianwuXue-NOAA commented on parm/config/config.base
> +fi
Maybe only need the DOIAU = NO, since I was told the GEFS will not use IAU. However, I am not sure whether it will be changed. So I keep these statements from config.base from g-w. In the future, we can delete unused statements.

2023-05-02 12:31 UTC, XianwuXue-NOAA commented on parm/config/config.fcst
> +echo "END: config.fcst"
This is just a reference of the Code segment from config.fcst in g-w, then we can easily compare the two config files. We can finalize it after the coupled fcst or aero fcst is ready.

2023-05-02 12:34 UTC, XianwuXue-NOAA commented on parm/config/config.fcst
> +export cplwav=${cplwav:-.true.}
Yes, however, I don't want to change the cplwav and cplchm until I work on the fcst with wave and/or cplchm. Otherwise, I can not test them to see whether I did the right changes or not.

2023-05-02 12:38 UTC, XianwuXue-NOAA commented on parm/config/config.fcst
> +    export AERO_EMIS_FIRE=$( echo "${AERO_EMIS_FIRE:-none}" | awk '{ print tolower($1) }' )
This is the copy from config.fcst in g-w. I don't want to change the scripts related DO_AERO until I do the aerol-fcst job. If you want to change it, please change it in config.fcst. I will do the update.

2023-05-02 12:40 UTC, XianwuXue-NOAA commented on parm/config/config.fcst
> +if [[ "$DO_WAVE" = "YES" && "$WAVE_CDUMP" != "gdas" ]]; then
This is the copy of code segments from config.fcst in g-w, I will follow the the config.fcst of g-w changes

2023-05-02 12:41 UTC, XianwuXue-NOAA commented on parm/config/config.fcst
> +fi
Since I am not working on aerosol-fcst job, so I don't want to include the changes for chem in atmos fcst

2023-05-02 12:44 UTC, XianwuXue-NOAA commented on parm/config/config.fcst
> +export FNSOTC=$FIX_AM/global_soiltype.statsgo.t$MTNRSL.rg.grb
after I removed these variables here, then the fcst will fail. So I add them back. I don't know who will test it, could you please let others to know this issue. Because someone resolve this issue, I think it is better to keep them, otherwise, the fcst will fail. @WalterKolczynski-NOAA @aerorahul

2023-05-02 12:47 UTC, XianwuXue-NOAA commented on rocoto/bin/hera/forecast_hr.sh
> +export ROTDIR=${COMROOT}/gefs/${ver}
GEFS will not use EXPDIR, This line is to set ROTDIR because I call j-job. This is only be used on Hera.

2023-05-02 12:48 UTC, XianwuXue-NOAA commented on rocoto/bin/hera/forecast_hr.sh
> +export ROTDIR_GFS=${HOMEdata}/gfs/${gfs_ver}
Yes, however, this is only used on Hera. On wcos2, I will use compath.py to get the path, but it can not used on Hera.

2023-05-02 12:52 UTC, XianwuXue-NOAA commented on parm/config/config.base
> +    echo "Unrecognized APP: ${1}"
> Didn't complete the review of the config files. It seems like a lot of GEFS settings were tacked on to GFS settings without considering whether they are still needed or to update them to match the GFS style (for instance, using `$cplchm` for branching instead of `$DO_AERO`). Many settings have been updated for GFS v17/GEFS v13 and we should defer to the new settings as given in GFS unless there is a good reason to deviate (like turning on stochastic physics for some members). Please carefully review all of the settings and determine whether it is conflicting with an existing setting elsewhere. If you have any trouble determining whether a setting should be overridden for GEFS, I'll help and if necessary we'll ask MDAB.
> 
> Also, note the changes that were made in the [NOAA-EMC/global-workflow#1509](https://github.com/NOAA-EMC/global-workflow/pull/1509). You've updated the commit hash, but there are changes to the config files that will need to be duplicated here.

Thanks @WalterKolczynski-NOAA this PR is for atmos fcst job only, so I don't want to do the change related cplwav and cplchm. I will do the changes when I work on the fcst for wave and/or aerosol.
Regarding the config files, I will compare them in g-w and do the corresponding changes.

2023-05-02 14:06 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +export CDATE=$PDY$cyc
Update `config.nsst` to use `$PDY` and `$cyc`

2023-05-02 14:09 UTC, WalterKolczynski-NOAA commented on parm/config/config.fcst
> +export FNSOTC=$FIX_AM/global_soiltype.statsgo.t$MTNRSL.rg.grb
IIRC, you had one member fail because of instability. That doesn't mean we should be using the old fix files.

2023-05-02 14:32 UTC, XianwuXue-NOAA commented on jobs/JGEFS_FORECAST
> +export CDATE=$PDY$cyc
Will you update the config.nsst in g-w? I will not copy the config.nsst to GEFS repo.

2023-05-02 14:37 UTC, XianwuXue-NOAA commented on jobs/JGEFS_FORECAST
> +  export WRDIR=${WRDIR:-$(compath.py $envir/com/$NET/${ver})}/${RUN}.${last_PDY}/$last_cyc/wave/restart
I will delete this block since it seems that we don't need it

2023-05-02 14:37 UTC, WalterKolczynski-NOAA commented on jobs/JGEFS_FORECAST
> +export CDATE=$PDY$cyc
Just leave it then until we remove it in g-w

2023-05-02 14:38 UTC, XianwuXue-NOAA commented on parm/config/config.base
> +fi
I will delete the DOIAU=YES condition.

2023-05-03 00:03 UTC, XianwuXue-NOAA commented on parm/config/config.fcst
> +export FNSOTC=$FIX_AM/global_soiltype.statsgo.t$MTNRSL.rg.grb
I have removed them and ran it on WCOSS2 successfully (c00, p01, p02)

2023-05-03 00:08 UTC, XianwuXue-NOAA commented
@WalterKolczynski-NOAA @aerorahul I have decided the config.fcst into two files: config.fcst and config.efcs. Which will shorten the config.fcst. Please re-review my changes for this PR. I think I have resolved all the comments. If I missed something, please let me know.

2023-05-04 22:54 UTC, XianwuXue-NOAA commented
Since the GEFSv13 workflow will be in g-w, I will merge this PR to close this PR and for the future's reference. I will do the same PR for the other jobs. If you have any suggestions, please let me know. @WalterKolczynski-NOAA @aerorahul

2023-05-04 23:10 UTC, merged