Hotfix/pqpf
NOAA-EMC/GEFS pull request #3
Opened 2020-11-25 18:30 UTC by DingchenHou-NOAA

2020-11-25 18:43 UTC, WalterKolczynski-NOAA requested changes
Needs some minor changes, mostly for formatting.

2020-11-25 18:43 UTC, WalterKolczynski-NOAA commented on scripts/exgefs_atmos_enspost.sh
>  export CDATE=$PDY$cyc;
This block is not properly indented

2020-11-25 18:43 UTC, WalterKolczynski-NOAA commented on scripts/exgefs_atmos_enspost.sh
> +    $CNVGRIB -g21 $DATA/$file $DATA/$file\_grb1
Use { } to denote the variable name boundary rather than escaping the underscore, as is done other places in this block.

2020-11-25 18:43 UTC, WalterKolczynski-NOAA commented on sorc/global_enspqpf.fd/PQPF.f90
> +if(iret.ne.0) goto 1020
This will need to be rewritten to remove the goto statements.

2020-11-27 15:49 UTC, XianwuXue-NOAA requested changes

2020-11-27 15:49 UTC, XianwuXue-NOAA commented on scripts/exgefs_atmos_enspost.sh
> +    $CNVGRIB -g21 $DATA/$file $DATA/$file\_grb1
agree

2020-11-27 15:53 UTC, XianwuXue-NOAA commented on sorc/global_enspqpf.fd/PQPF.f90
> +if(iret.ne.0) goto 1020
I modified this file to remove the "goto"statement, however, I used wrong reference number (#3 for this PR instead of #2), so Please check my changes and if it is OK, Dingchen can merge it into his branch for this PR.

2020-12-01 19:37 UTC, DingchenHou-NOAA commented
Working with Xianwu, I have addressed the comments.

2020-12-01 19:42 UTC, WalterKolczynski-NOAA approved these changes

2020-12-01 19:54 UTC, XianwuXue-NOAA approved these changes

2020-12-01 20:28 UTC, merged