Tuning and/or Optimise resources request for WCOSS2
NOAA-EMC/GEFS pull request #34
Opened 2021-10-08 21:26 UTC by DingchenHou-NOAA

1) The change is mainly in the lsf files in rocoto/dev/lsf/wcoss2
2) A few wave-related J-jobs are modified to reset the default of tasks

Refs: #23

2021-10-08 21:44 UTC, XianwuXue-NOAA requested changes

2021-10-08 21:44 UTC, XianwuXue-NOAA commented on rocoto/dev/lsf/wcoss2/d0_16/wave/jgefs_wave_post.ecf
>  module load grib_util/$grib_util_ver
Need add "module load libjpeg/$libjpeg_ver" before the grim_util

2021-10-08 21:44 UTC, XianwuXue-NOAA commented on rocoto/dev/lsf/wcoss2/d16_35/atmos/jgefs_atmos_post.ecf
> +export gefsmpexec="mpiexec -n $total_tasks"
I think you can comment this line since I have added it to the default value to j-job for gefsmpexec.

2021-10-08 21:44 UTC, XianwuXue-NOAA commented on rocoto/dev/lsf/wcoss2/d16_35/atmos/jgefs_atmos_prdgen.ecf
> +#PBS -l walltime=3:30:00
In production, we use 4:30 as default value for walltime.

2021-10-08 21:44 UTC, XianwuXue-NOAA commented on rocoto/dev/lsf/wcoss2/post_processing/d16_35/atmos/jgefs_atmos_ensstat.ecf
>  module load grib_util/$grib_util_ver
Move "module load libjpeg/$libjpeg_ver" to before loading grid_util

2021-10-08 21:44 UTC, XianwuXue-NOAA commented on rocoto/dev/lsf/wcoss2/d0_16/jgefs_forecast.ecf
> +export npe_wav=88 #120
Some of the variables will update j-job as default value, I plan to do the final test next week to confirm your settings.

2021-10-12 14:12 UTC, DingchenHou-NOAA commented on rocoto/dev/lsf/wcoss2/d0_16/jgefs_forecast.ecf
> +export npe_wav=88 #120
I agree!

2021-10-12 14:15 UTC, DingchenHou-NOAA commented
Xianwu,
     If you feel we can do the merge now, please do so.

2021-10-12 14:26 UTC, XianwuXue-NOAA commented on rocoto/dev/lsf/wcoss2/post_processing/d16_35/atmos/jgefs_atmos_ensstat.ecf
>  module load grib_util/$grib_util_ver
You should add "module load libjpeg/$libjpeg_ver" before loading grid_util. Otherwise, it will cause error.

2021-10-12 14:27 UTC, XianwuXue-NOAA approved these changes

2021-10-12 14:28 UTC, merged