Convert module files on WCOSS2 to Lua format
NOAA-EMC/GEFS pull request #99
Opened 2023-01-23 15:02 UTC by XianwuXue-NOAA

2023-01-23 15:35 UTC, WalterKolczynski-NOAA requested changes

2023-01-23 15:35 UTC, WalterKolczynski-NOAA commented on sorc/build_gefs_anom2_fcst.sh
> +	module load ${progname}.${target}.lua
You don't need the `.lua` suffix here.

2023-01-23 15:35 UTC, WalterKolczynski-NOAA commented on sorc/build_gefs_anom2_fcst.sh
> +if [[ $target == "wcoss2" ]]; then
Why are you using two different methods for module loading?

2023-01-23 15:43 UTC, XianwuXue-NOAA commented on sorc/build_gefs_anom2_fcst.sh
> +if [[ $target == "wcoss2" ]]; then
This is to make it compatible with other machines, such as Hera. After I change the modules to Lua on Hera, then it will be only one method for module loadings.

2023-01-23 15:45 UTC, XianwuXue-NOAA commented on sorc/build_gefs_anom2_fcst.sh
> +	module load ${progname}.${target}.lua
Thanks for pointing this, I have  tested removing .lua, and it works well. I will put a comment for this.

2023-01-23 15:46 UTC, WalterKolczynski-NOAA commented on sorc/build_gefs_anom2_fcst.sh
> +if [[ $target == "wcoss2" ]]; then
I think you'd be better off just updating to lua for all machines at once.

2023-01-23 15:47 UTC, XianwuXue-NOAA commented on sorc/build_gefs_anom2_fcst.sh
> +if [[ $target == "wcoss2" ]]; then
OK. I will do that.

2023-01-23 16:24 UTC, XianwuXue-NOAA commented on sorc/build_gefs_anom2_fcst.sh
> +if [[ $target == "wcoss2" ]]; then
I have convert Hera module files to lua format and also unified the module loading methods

2023-01-23 22:52 UTC, XianwuXue-NOAA commented
@WalterKolczynski-NOAA I have converted the module files for Hera and also unified the build_*.sh scripts

2023-01-25 19:37 UTC, XianwuXue-NOAA commented
@WalterKolczynski-NOAA When you have time, could you please review my changes? After you approved it, I will merge it and do the bugzilla issues. Thanks,

2023-01-27 22:11 UTC, WalterKolczynski-NOAA approved these changes

2023-01-27 22:13 UTC, merged